import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { MerkleTree } from 'merkletreejs'
import keccak256 from 'keccak256'

declare let window: any;

const whitelistAddresses: any = ['0x4ae70b51e3c82da5be3284d90325ffa1898340d7', '0x4ae70b51e3c82da5be3284d90325ffa1898340d7']

const Home: NextPage = () => {
  const leafNodes = whitelistAddresses.map((addr: any) => keccak256(addr))
  const merkleTree = new MerkleTree(leafNodes, keccak256, {sortPairs: true})
  const [verify, setVerify] = useState(false)
  const [accounts, setAccounts] = useState([])

  useEffect(() => {
    fetchWhitelist()
  }, [])
  const fetchWhitelist = async () => {
    const newAccounts = await window.ethereum.request({
      method: "eth_requestAccounts",
    });
    const rootHash = merkleTree.getRoot()
    const claimingAddress = keccak256(newAccounts[0])
    const hexProof = await merkleTree.getHexProof(claimingAddress)
    const verify = merkleTree.verify(hexProof, claimingAddress, rootHash)
    setVerify(verify)
    setAccounts(newAccounts)
    console.log(verify)
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a href = 'https://twitter.com/memelordnfts'>
      <img src='https://cdn4.iconfinder.com/data/icons/social-media-icons-the-circle-set/48/twitter_circle-512.png' id='logo' />
      </a>
      <a href = 'https://opensea.io/collection/memelordsofficial'>
      <img src='https://user-images.githubusercontent.com/35243/140804979-0ef11e0d-d527-43c1-93cb-0f48d1aec542.png' id='logo' />
      </a>
      <br />
      <br />
      <br />
      <h1> Meme Lords Whitelist Checker </h1>
      {accounts.length == 0 && <h2>Your wallet is not connected</h2>}
      {accounts.length > 0 && <h2>{verify ? 'You are whitelisted' : 'You are not whitelisted'}</h2>}
    </div>
  )
}

export default Home
